### ISSUE TITLE
Helm support

### ISSUE THREAD

**Issue by andpozo** [controlplaneio/kubesec#142]
Hey guys, any plan or way to analize a helm chart with `kubesec`?

**Comment by 06kellyjac** [comment]
Hi @andpozo, you can do that right now with `helm template` to locally render the yaml & some standard unix tools

```
$ helm template my-release bitnami/metrics-server > out.yml

$ kubesec scan out.yml
[
  {
    "object": "ServiceAccount/my-release-metrics-server.default",
    "valid": true,
    "message": "This resource kind is not supported by kubesec",
    "score": 0,
    "scoring": {}
  },
  # ...
]
```

Or you can pipe it straight in:

`helm template my-release bitnami/metrics-server | kubesec scan -`

(Note: `-` only works on newer versions of kubesec [since `v2.6.0` I believe] but even with old kubesec `helm template my-release bitnami/metrics-server | kubesec scan /dev/stdin` should work)


LMK if this helps you with your use-case.

**Comment by andpozo** [comment]
hey @06kellyjac make sense completely and works as expected, thanks a lot!
