### ISSUE TITLE
Release does not include binaries

### ISSUE THREAD

**Issue by kmcquade** [controlplaneio/kubesec#53]
The link is incorrect in the README

> Linux/MacOS/Win binary (get the latest release)

And the release does not include the binaries

**Comment by sublimino** [comment]
Thanks @kmcquade! Quality bio :rofl: 

1) link fixed in https://github.com/controlplaneio/kubesec/commit/c09700148b299b61d06b392031f6e1eada4be543

2) we had [`goreleaser`](https://github.com/controlplaneio/kubesec/blob/master/.goreleaser.yml) for this but I think it's now just [makefile-driven](https://github.com/controlplaneio/kubesec/blob/master/Makefile#L98) - @stefanprodan do we have a plan for this or shall I just build and upload a Linux binary to get started?

**Comment by adamdecaf** [comment]
FYI, this project was posted to reddit so it'll have some visitors (hi!). 

https://www.reddit.com/r/kubernetes/comments/d2m5o3/i_just_noticed_that_kubesecio_was_open_sourced/

Can we get binaries released?

**Comment by jesmg** [comment]
It would be very useful to have the binaries in the release!

It should be done automatically? How? I offer myself to try to do it, if you give me more details.

**Comment by stefanprodan** [comment]
We already use goreleaser so let’s go with GitHub actions https://goreleaser.com/actions/

**Comment by 06kellyjac** [comment]
Binaries are released since #68 was merged
